
version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - SQLITE_PATH=sqlite.db
    volumes:
      - .:/code
    command: uvicorn main:app --host 0.0.0.0 --port 80
  
  litestream:
    image: litestream/litestream
    volumes:
      - "./litestream.yml:/etc/litestream.yml"
      - "./data/sqlite.db:/sqlite.db"
    command: replicate